# Set the project language
language: shell

# Install build dependencies
install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install git devscripts shunit2 openssh-client openssh-server

# Setup SSH infrastructure necessary to run tests
before_script:
  - scripts/ci-setup-xeno.sh
  - scripts/ci-setup-ssh.sh

# Install externals and build
script:
  - checkbashisms xeno
  - shunit2 scripts/ci-test-xeno.sh
  - shunit2 scripts/ci-test-xeno-config.sh
  - shunit2 scripts/ci-test-xeno-daemon.sh
  - shunit2 scripts/ci-test-file-edit.sh
  - shunit2 scripts/ci-test-directory-edit.sh

# Send notifications
notifications:
  email:
    - jacob@havoc.io
